using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using Newtonsoft.Json.Linq;
using McpUnity.Unity;
using McpUnity.Utils;

namespace McpUnity.Tools
{
    /// <summary>
    /// Tool for saving Unity scenes without requiring human intervention.
    /// </summary>
    public class SaveSceneTool : McpToolBase
    {
        public SaveSceneTool()
        {
            Name = "save_scene";
            Description = "Saves the active scene or all open/modified scenes. If the scene is untitled and no path is specified, it automatically saves to Assets/Scenes/ without prompting.";
        }

        /// <summary>
        /// Execute the SaveScene tool with the provided parameters
        /// </summary>
        /// <param name="parameters">Tool parameters as a JObject</param>
        public override JObject Execute(JObject parameters)
        {
            string scenePath = parameters["scenePath"]?.ToObject<string>();
            bool saveAs = parameters["saveAs"]?.ToObject<bool?>() ?? false;
            bool saveAllModified = parameters["saveAllModified"]?.ToObject<bool?>() ?? false;

            try
            {
                // Mode 1: Save all modified / open scenes
                if (saveAllModified)
                {
                    var savedScenes = new JArray();
                    int sceneCount = SceneManager.sceneCount;

                    for (int i = 0; i < sceneCount; i++)
                    {
                        Scene scene = SceneManager.GetSceneAt(i);
                        if (!scene.isLoaded) continue;

                        if (scene.isDirty || string.IsNullOrEmpty(scene.path))
                        {
                            string target = scene.path;
                            bool autoGenerated = false;

                            if (string.IsNullOrEmpty(target))
                            {
                                string defaultFolder = "Assets/Scenes";
                                EnsureDirectoryExists(defaultFolder);
                                string sceneName = string.IsNullOrEmpty(scene.name) || scene.name.StartsWith("Untitled", StringComparison.OrdinalIgnoreCase)
                                    ? "Untitled"
                                    : scene.name;
                                target = AssetDatabase.GenerateUniqueAssetPath($"{defaultFolder}/{sceneName}.unity");
                                autoGenerated = true;
                            }

                            bool ok = EditorSceneManager.SaveScene(scene, target);
                            if (ok)
                            {
                                savedScenes.Add(new JObject
                                {
                                    ["name"] = scene.name,
                                    ["path"] = target,
                                    ["autoGeneratedPath"] = autoGenerated
                                });
                            }
                        }
                    }

                    AssetDatabase.Refresh();

                    return new JObject
                    {
                        ["success"] = true,
                        ["type"] = "text",
                        ["message"] = $"Successfully saved {savedScenes.Count} modified scene(s)",
                        ["savedCount"] = savedScenes.Count,
                        ["savedScenes"] = savedScenes
                    };
                }

                // Mode 2: Save active scene
                Scene activeScene = SceneManager.GetActiveScene();

                if (!activeScene.IsValid())
                {
                    return McpUnitySocketHandler.CreateErrorResponse(
                        "No valid active scene to save",
                        "validation_error"
                    );
                }

                string targetPath;
                bool isAutoGenerated = false;

                if (saveAs || !string.IsNullOrEmpty(scenePath))
                {
                    // Save As mode - need a path
                    if (string.IsNullOrEmpty(scenePath))
                    {
                        return McpUnitySocketHandler.CreateErrorResponse(
                            "Parameter 'scenePath' is required when 'saveAs' is true",
                            "validation_error"
                        );
                    }

                    // Ensure the path has .unity extension
                    if (!scenePath.EndsWith(".unity", StringComparison.OrdinalIgnoreCase))
                    {
                        scenePath += ".unity";
                    }

                    // Ensure the path starts with Assets/
                    if (!scenePath.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
                    {
                        scenePath = "Assets/" + scenePath;
                    }

                    // Ensure the directory exists
                    string directory = System.IO.Path.GetDirectoryName(scenePath);
                    EnsureDirectoryExists(directory);

                    targetPath = scenePath;
                }
                else
                {
                    // Save to current path, or auto-fallback if untitled
                    targetPath = activeScene.path;

                    if (string.IsNullOrEmpty(targetPath))
                    {
                        // Automatic fallback for untitled scenes: save to Assets/Scenes/ without prompting
                        string defaultFolder = "Assets/Scenes";
                        EnsureDirectoryExists(defaultFolder);
                        string sceneName = string.IsNullOrEmpty(activeScene.name) || activeScene.name.StartsWith("Untitled", StringComparison.OrdinalIgnoreCase)
                            ? "Untitled"
                            : activeScene.name;
                        targetPath = AssetDatabase.GenerateUniqueAssetPath($"{defaultFolder}/{sceneName}.unity");
                        isAutoGenerated = true;
                    }
                }

                bool saved = EditorSceneManager.SaveScene(activeScene, targetPath);

                if (!saved)
                {
                    return McpUnitySocketHandler.CreateErrorResponse(
                        $"Failed to save scene to '{targetPath}'",
                        "save_error"
                    );
                }

                AssetDatabase.Refresh();

                McpLogger.LogInfo($"Saved scene '{activeScene.name}' to path '{targetPath}' (autoPath: {isAutoGenerated})");

                return new JObject
                {
                    ["success"] = true,
                    ["type"] = "text",
                    ["message"] = isAutoGenerated
                        ? $"Successfully saved untitled scene '{activeScene.name}' to auto-generated path '{targetPath}' without human intervention"
                        : $"Successfully saved scene '{activeScene.name}' to '{targetPath}'",
                    ["scenePath"] = targetPath,
                    ["sceneName"] = activeScene.name,
                    ["autoGeneratedPath"] = isAutoGenerated
                };
            }
            catch (Exception ex)
            {
                return McpUnitySocketHandler.CreateErrorResponse(
                    $"Error saving scene: {ex.Message}",
                    "scene_save_error"
                );
            }
        }

        /// <summary>
        /// Ensures directory exists under Assets/
        /// </summary>
        private void EnsureDirectoryExists(string folderPath)
        {
            if (string.IsNullOrEmpty(folderPath)) return;
            if (AssetDatabase.IsValidFolder(folderPath)) return;

            string[] parts = folderPath.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
            string current = parts.Length > 0 && parts[0] == "Assets" ? "Assets" : "Assets";

            for (int i = 0; i < parts.Length; i++)
            {
                if (i == 0 && parts[i] == "Assets") continue;

                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }
                current = next;
            }
        }
    }
}
